In [2]:
import numpy as np
arr=np.array([1,2,3,6,4,5])
reversed_arr=arr[::-1]
print(reversed_arr)

[5 4 6 3 2 1]


In [ ]:
array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
flatten1=array1.flatten()
print(flatten1)

[1 2 3 2 4 5 1 2 3]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
are_equal=np.array_equal(arr1,arr2)
print(are_equal)


True


In [ ]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
def most_frequent_indices(arr):
    counts=np.bincount(arr)
    value=np.argmax(counts)
    indices=np.where(arr==value)
    return value,indices
val_x, idx_x=most_frequent_indices(x)
val_y, idx_y=most_frequent_indices(y)
print(val_x)
print(val_y)
print(idx_x)
print(idx_y)


1
1
(array([0, 5, 7, 8, 9]),)
(array([0, 1, 2]),)


In [ ]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
sum_all=gfg.sum()
sum_rows=gfg.sum(axis=1)
sum_cols=gfg.sum(axis=0)
print(sum_all,sum_rows,sum_cols)

45 [[14]
 [16]
 [15]] [[20  9 16]]


In [ ]:
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
diag_sum=np.trace(n_array)
eigen_vals, eigen_vecs=np.linalg.eig(n_array)
inv=np.linalg.inv(n_array)
det=np.linalg.det(n_array)
print("sum of diagonal: ",diag_sum)
print("Eigen values: ",eigen_vals)
print("Eigen vectors: ",eigen_vecs)
print("Inverse of matrix: ",inv)
print("Determinant: ",det)

sum of diagonal:  176
Eigen values:  [98.16835147 28.097044   49.73460452]
Eigen vectors:  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix:  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant:  137180.0000000001


In [ ]:
p1=np.array([[1,2],[2,3]])
q1=np.array([[4,5],[6,7]])
product1=np.dot(p1,q1)
cov1=np.cov(p1.T, q1.T)
p2=np.array([[1,2],[2,3],[4,5]])
q2=np.array([[4,5,1],[6,7,2]])
product2=np.dot(p2,q2)
cov2=np.cov(np.hstack((p2.T,q2)))
print("Product1= ",product1)
print("cov1= ",cov1)
print("Product2= ",product2)
print("cov2= ",cov2)

Product1=  [[16 19]
 [26 31]]
cov1=  [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]
Product2=  [[16 19  5]
 [26 31  8]
 [46 55 14]]
cov2=  [[2.96666667 3.63333333]
 [3.63333333 4.56666667]]


In [ ]:
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
inner_prod=np.inner(x,y)
outer_prod=np.outer(x,y)
cartesian_prod=np.array(np.meshgrid(x.flatten(),y.flatten())).T.reshape(-1,2)
print("Inner product= ",inner_prod)
print("Outer product= ",outer_prod)
print("Cartesian product= ",cartesian_prod)

Inner product=  [[17 52]
 [13 62]]
Outer product=  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product=  [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [4]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
print("Absolute:\n", np.abs(array))

print("Flattened percentiles:", np.percentile(array, [25, 50, 75]))
print("Column-wise percentiles:\n", np.percentile(array, [25, 50, 75], axis=0))
print("Row-wise percentiles:\n", np.percentile(array, [25, 50, 75], axis=1))


print("Mean(flatten):", np.mean(array))
print("Mean(column):", np.mean(array, axis=0))
print("Mean(row):", np.mean(array, axis=1))

print("Median(flatten):", np.median(array))
print("Median(column):", np.median(array, axis=0))
print("Median(row):", np.median(array, axis=1))

print("Std(flatten):", np.std(array))
print("Std(column):", np.std(array, axis=0))
print("Std(row):", np.std(array, axis=1))




Absolute:
 [[1 2 3]
 [4 5 6]]
Flattened percentiles: [-3.5 -0.5  2.5]
Column-wise percentiles:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Row-wise percentiles:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean(flatten): -0.5
Mean(column): [-1.5  1.5 -1.5]
Mean(row): [ 0.66666667 -1.66666667]
Median(flatten): -0.5
Median(column): [-1.5  1.5 -1.5]
Median(row): [ 1. -4.]
Std(flatten): 3.8622100754188224
Std(column): [2.5 3.5 4.5]
Std(row): [2.05480467 4.78423336]


In [3]:
a=np.array([-1,8,-1.6,-0.5,0.5,1.6,1.8,3.0])
floor_val=np.floor(a)
ceil_val=np.ceil(a)
trunc_val=np.trunc(a)
round_val=np.round(a)
print("Floor val= ",floor_val)
print("Ceil val= ",ceil_val)
print("Trunc val= ",trunc_val)
print("Round val= ",round_val)

Floor val=  [-1.  8. -2. -1.  0.  1.  1.  3.]
Ceil val=  [-1.  8. -1. -0.  1.  2.  2.  3.]
Trunc val=  [-1.  8. -1. -0.  0.  1.  1.  3.]
Round val=  [-1.  8. -2. -0.  0.  2.  2.  3.]


In [6]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted:", np.sort(array))
print("Sorted indices:", np.argsort(array))
print("4 smallest:", np.sort(array)[:4])
print("5 largest:", np.sort(array)[-5:])


array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
ints = array[array == array.astype(int)]
floats = array[array != array.astype(int)]
print("Integer elements:", ints)
print("Float elements:", floats)


Sorted: [ 10  16  16  52  54  62 453]
Sorted indices: [0 3 4 1 5 2 6]
4 smallest: [10 16 16 52]
5 largest: [ 16  52  54  62 453]
Integer elements: [1. 2. 3. 2.]
Float elements: [1.2 2.2]


In [7]:
from PIL import Image


def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:
        np.savetxt("grayscale_image.txt", arr, fmt='%d')
    else:
        reshaped = arr.reshape(-1, arr.shape[-1])
        np.savetxt("rgb_image.txt", reshaped, fmt='%d')


def load_saved(file_path):
    data = np.loadtxt(file_path, dtype=int)
    print(data)
    return data


